title:              Making it up as i Go!
bio:                'Hey there! This is Guru. This site keeps things I find interesting along with some of my writings.
                    So, feel free to wonder around and take a look at what I am curious about!'
description:        "The difference between drunk fish and a drunk man is that the man always reaches home."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/dog_courage.jpg'
background:         'assets/img/feynman-1-3.png'
tiled_bg:           false
locale:             en_US
url:                https://guruzeta.github.io/sun/

permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

collections:
  miscellaneous:
    output: true
    permalink: /:collection/:path/

disqus_shortname:   guruzeta

email:              gurukalyan1.618@gmail.com
github-url:         Guruzeta/sun

plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
